#classic guitar
print("        ___")
print("      o|* *|o")
print("      o|* *|o")
print("      o|* *|o")
print("       \===/")
print("        |||")
print("        |||")
print("     ___|||___")
print("    /   |||   \ ")
print("   /    |||    \ ")
print("  |     |||     |")
print("   \   (|||)   /")
print("    |   |||   |")
print("   /    |||    \ ")
print("  /     |||     \ ")
print(" /      |||      \ ")
print(" |     [===]     |")
print("  \             /")
print("   '._________.'")
#retro guitar
print("       ._-_.")
print("      +|\G/|+")
print("      +|\./|+")
print("      +|\./|+")
print("       \===/")
print("        |||")
print("        |||")
print("     ___|||___")
print("    /   |||   \ ")
print("   /    |||    \ ")
print("  |     |||     |")
print("   \   (|||)   /")
print("    |   |||   |")
print("   /    |||    \ ")
print("  /     |||     \ ")
print(" /      |||      \ ")
print(" |     [===]     |")
print("  \             /")
print("   '._________.'")
#long guitar
print("        ___")
print("      o|* *|o")
print("      o|* *|o")
print("      o|* *|o")
print("       \===/")
print("        |||")
print("        |||")
print("        |||")
print("        |||")
print("     ___|||___")
print("    /   |||   \ ")
print("   /    |||    \ ")
print("  |     |||     |")
print("   \   (|||)   /")
print("    |   |||   |")
print("   /    |||    \ ")
print("  /     |||     \ ")
print(" /      |||      \ ")
print(" |     [===]     |")
print("  \             /")
print("   '._________.'")